source('function_win_rate.R')

win_rate("input/winlog1.csv",1)
win_rate("input/winlog2.csv",2)
win_rate("input/winlog3.csv",3)
win_rate("input/winlog4.csv",4)
win_rate("input/winlog5.csv",5)
win_rate("input/winlog6.csv",6)
win_rate("input/winlog7.csv",7)
win_rate("input/winlog8.csv",8)
win_rate("input/winlog9.csv",9)
win_rate("input/winlog0.csv",0)